name: ZeroRespawn
main: com.daytonjwatson.zerorespawn.ZeroRespawnPlugin
version: 1.0.0
api-version: 1.20
author: Dayton
description: "Hardcore plugin: die once, no respawn."

commands:
  zerorespawn:
    description: Main command for ZeroRespawn
    usage: "/<command> [info|reload]"
    aliases: [zr, hardcore]

  guide:
    description: "Receive the ZeroRespawn guide book."
    aliases: [book]

  stats:
    description: "View survival statistics."
    usage: "/stats [player]"

  note:
    description: "Manage coordinate notes"
    usage: "/note <add|list|remove>"

  msg:
    description: "Send a private message to a player."
    usage: "/msg <player> <message>"

  r:
    description: "Reply to the last private message."
    usage: "/r <message>"
  
  help:
    description: "Show ZeroRespawn-specific help menu."
    usage: "/help [command]"


permissions:
  zerorespawn.command:
    description: "Use /zerorespawn info."
    default: true

  zerorespawn.admin:
    description: "Reload ZeroRespawn configuration."
    default: op

  zerorespawn.guide:
    description: "Receive the guide book."
    default: true

  zerorespawn.stats:
    description: "View personal stats."
    default: true

  zerorespawn.stats.others:
    description: "View other players' stats."
    default: op

  zerorespawn.note:
    description: "Manage personal notes."
    default: true
